# Import library
library(DBI)
library(C50)

# Menghubungkan ke database
con <- DBI::dbConnect(odbc::odbc(), 
                .connection_string = "Driver={MySQL ODBC 8.0 Unicode Driver};", 
                Server = "localhost", Database = 'new_posproject', UID = 'root', PWD = '123456',
                Port = 3306, bigint = 'integer')

# Mengambil data dari database menggunakan query sql
data <- dbGetQuery(con,'SELECT companies.id AS company_id, users.name, pp.capital_price, SUM(pp.capital_price*products.quantity) as actual_cap, COUNT(pp.created_at) as total_transactions, 1 as "risk_score"
                        FROM companies
                          INNER JOIN users
                          ON companies.id = users.id
                          INNER JOIN product_prices AS pp
                          ON companies.id = pp.company_id
                          INNER JOIN products
                          ON companies.id = products.company_id
                          GROUP BY companies.id
                          ')

#Labeling data                          
data$risk_score <- c(1, 3, 2, 1, 2)
# data$risk_score <- data$capital_price * data$total_transactions <<< Untuk menghitung FICO Score
                          
# Pemilihan feature
input_columns <- c("capital_price", "actual_cap", 'total_transactions')

data$risk_score <- as.factor(data$risk_score)

df <- data[, input_columns]

set.seed(100)

# Pemisahan training set dan test set
indeks_training_set <- sample(900, 800)
input_training_set <- df[indeks_training_set,]
class_training_set <- data[indeks_training_set,]$risk_score
input_testing_set <- df[-indeks_training_set,]

# Creating model
risk_rating_model <- C5.0(input_training_set, class_training_set, control = C5.0Control(label="Risk Rating"))

# Predicting
pospredict <- function(capital_price, actual_cap, total_transactions){
  newdata <- data.frame(capital_price = as.numeric(capital_price), actual_cap = as.numeric(actual_cap), total_transactions = as.numeric(total_transactions))
  predict(risk_rating_model, newdata, type = 'prob')
}

# Ringkasan hasil model
summary(risk_rating_model)

# Testing menggunakan test set
predict(risk_rating_model, input_testing_set)

# Testing untuk data yang bbaru
print(pospredict(40000, 7051230, 25))

# Pembuatan API
saveRDS(risk_rating_model, 'API/POSapp_model.rds')
#save(risk_rating_model, file = "API/POSapp_model.RData")
              
